var arrLang = {
	'kz':{
		'main':'Басты',
		'help':'Көмектесіңдер',
		'tour':'Сапар',
		'main2':'Қазақстанның қасиетті жерлері',
		'inform':'Ең танымал мәдени мұра объектілері туралы ақпарат',
		'more':'Толығырақ',
		'Otpan':'Отпантау - тарихи-мәдени кешен, кесене. 2007 жылы 25 қазанда ашылды. Кешен 2004 жылы С.Адайдың бастамасымен салынған.',
		'Kaindy':'Қайыңды - Қазақстанның Алматы облысындағы көл, Күнгей Алатау шатқалдарының бірінде танымал туристік бағыт.',
		'Arystan':'Арыстан-Баб - ұстаз және рухани тәлімгер Қожа Ахмет Ясауидің қабіріндегі кесене. Кесене Шымкент қаласынан 150 шақырым жерде орналасқан.',
		'Ak':'Ақмечет-Әулие - Қазақстанның Түркістан аймағындағы үңгір.',
		'A':'Ақмечет-Әулие',
		'Ch':'Шарын каньоны',
		'Charyn':'Шарын каньоны - Қазақстандағы Шарын өзені бойындағы ұзындығы 154 км болатын каньон.',
		'Our':'Біздің әлеуметтік желілер:',
		'Our2':'Біздің пошта:',
		'c_tour':'Қазақстанның қасиетті жерлеріндегі туризм',
		'c_text': 'Қазақстанға саяхат - бұл таңғажайып табиғи ландшафтарға, жергілікті тұрғындардың қонақжайлылығына және ұлттық тағамдардың алуан түрлілігіне толы нағыз шытырман оқиға. Еуропа мен Азияның түйіскен жерінде орналасқан бұл ел түрлі мәдени және діни ағымдардың әсерін бойына сіңірді. Бұл жерде мыңдаған жылдар бойы өзендер маңындағы кең аңғарларда және көркем тау бөктерінде мал бағумен айналысқан көшпенділер өмір сүрген.Тікелей аудармада «қазақ» сөзі «еркін адам» дегенді білдіреді, яғни Қазақстан - бұл ел көршілерімен бейбіт өмір сүретін және оның тарихымен мақтанатын бостандықты сүйетін адамдар. Жеке мемлекет ретінде Қазақстан Республикасы әлемнің геосаяси картасында КСРО ыдырағаннан кейін 1991 жылы пайда болды. Алайда, көптеген ғасырлар бойы қазақ халқы өзінің ерекше құндылықтарын өсірді, ежелгі дәстүрлерді ұстанды, олардың тағамдарын, музыкасын, халықтық билерін өсірді ... Бүгін Қазақстан әлемдегі ең үлкен елдердің бірі болып табылады, ол өзінің қонақтарының қиялын таң қалдырады барлық қабаттар мен ерекшеліктердегі әртүрлілік.жергілікті өмір. Қазақстанға саяхатқа барыңыз - және бұл ел сізге өзінің ерекше хош иісіне айналған түстердің жарықтығын және талғамның анықтығын көрсетеді. ',		
		'c_tour2':'Қазақстанға әр түрлі маусымда саяхаттау',
		'c_text2': 'Қазақстан көктем мен күзде ең климатты климатқа ие, бірақ елдің көптігіне байланысты елдің әр түкпірінде әр уақытта жылы ауа-райын тамашалауға болады. Қыс шаңғы, сноуборд және коньки тебуге тамаша уақыт. . Мұны Алматыдағы заманауи шаңғы курорттары Медеу мен Шымбұлақта жасауға болады. Сондай-ақ, қыс - бұл Қазақстанның ірі қалаларында мұражайларға, бу моншаларына және мерекелік іс-шараларға барудың тамаша мүмкіндігі.Қазақстанда күзде көп нәрсе жасау керек, өйткені елдің көп бөлігі жарқын күзгі ландшафтармен жарықтандырылады, ал ауа райы жағдайлары жаяу серуендеуге және қалаларға және одан тыс жерлерге экскурсияға жақсы.Көктем - каньондарда серуендеу, петроглифтер, Оңтүстік Түркістан мен Шымкентке экскурсиялар мен қарлы таулар мен гүлденген шалғындардың көріністерін тамашалауға болатын пойызбен саяхаттайтын маусым. елдің оңтүстігінде ыстық, ал солтүстігінде қоңыржай. Жазда сіздер астананы зерттеп, Бурабай ұлттық саябағына баруға, Байқоңыр станциясына баруға немесе Ақтау маңындағы Каспий теңізіне баруға болады. «Қазақстанда не істеу керек?» Деген сұраққа жауап. жүздеген жауап нұсқалары арқылы ашылуы мүмкін. Елде сіздің сапарыңыздың баға жетпес күндерін белсенді, қызықты және пайдалы өткізуге шынымен бәрі бар. ',		
		'c_tour3':'Қазақстанға сапарға қанша күн бөлуге болады?',
		'c_text3': 'Нұр-Сұлтан және Алматы сияқты ірі қалалар туристік ағымның көп бөлігін алады. Олардың барлығы тарихи және заманауи көрнекіліктерден басқа ойын-сауық пен демалыстың кең спектрін ұсынады. Табиғи орындардың көпшілігінің асығыс туристердің назардан тыс қалуы ұят нәрсе. Егер сіз Қазақстанға шынымен де көңілді саяхатты жоспарлағыңыз келсе, біздің нұсқаулығымызды зерттеп, елдегі қызықты оқиғаларға арналған өзіңіздің жеке маршруттарыңызды жасаңыз: Нұр-Сұлтан (Астана) - Қазақстанның сәнді және заманауи қаласы, өзінің желді ауа-райымен және футуристік сәулетімен танымал. Бөлу үшін қанша уақыт? 1-2 күн Негізгі көрнекіліктер: Бәйтерек мұнарасы, Хан-Шатыр сауда орталығы, Бейбітшілік және Келісім сарайы.Толған жолдан қалай шығу керек: Бурабай ұлттық саябағына немесе Қорғалжын қорығына бір күндік саяхатқа барыңыз.Алматы - бұрынғы астана және ең үлкен қала елдің. Алматының архитектуралық келбеті кеңестік және заманауи стильдердің керемет үйлесімі болып табылады, қанша уақыт бөлуге болады? 1-2 күн Негізгі көрнекіліктер: Панфилов саябағы, Көк базар, Алматы аспалы жолымен Көк-Төбе. Үзілген жолдан қалай шығу керек: өз өмірін және экономикасын басқаратын ғұндардың этноауылына бару арқылы уақытқа сапар шегу. ғасырлар бұрынғы ата-бабалары сияқты. Әсерлі көріністерді сүйетіндер Алматы маңындағы биік таулы «Медеу» спорт кешеніне барып, конькимен сырғанауға және оның айналасындағы тау жоталарына қарайтын ландшафты бақылай алады.Алматы облысы - Алматы маңында сіз күндізгі саяхаттарға арналған көптеген орындарды таба аласыз. бөлуге уақытты бөлу керек пе? 2 күн (Алматыдан жолда кемпинг немесе күндізгі сапарлар) Негізгі көрікті жерлер: Шарын каньоны, Үлкен Алматы көлі, Түрген шатқалы және сарқырама. Соққы жолынан қалай шығу керек: Тамғалы петроглифтеріне сүйсіну немесе Алтын-Емел қорығындағы лагерь. ',		
		'c_text4': 'Шымкент - бұл Орталық Азияның атмосферасы керемет сақталған оңтүстік қала, оған қанша уақыт бөлу керек? 1-2 күн Негізгі көрнекіліктер: Құлует этнографиялық мұражайы, Абай саябағындағы еске алу аллеясы, Арбат көшесі. Ұзартылған жолдан қалай шығу керек: Сайрам ауылындағы кесенелер мен азық-түлік базарларын көріңіз немесе Ақсу-Жабағылы қорығындағы атқа мініңіз. Оңтүстік Қазақстанның астанасы, кішкентай, бірақ ежелгі қала және қасиетті қажылық орны - қанша уақыт бөлуге болады? 1-күн Негізгі көрікті жерлер: Қожа Ахмет Ясауидің жерасты мешіті, мұражайы, кесенелері және қабырғасы бар кешені. Ұзартылған жолдан қалай шығу керек: Арыстан-Баб кесенесінде діни зиярат етушілерге қосылыңыз немесе Отырардың қирандыларында қыдырыңыз Ақтау - алыс батыстағы қала. , өзінің мұнайымен танымал, Каспий теңізінің ұзын жағалау сызығы және Кавказға жақын орналасқан. Қанша уақыт бөлуге болады? 1-күн Негізгі көрнекіліктер: Республика алаңы, Ақтау жағалауы және теңіз айлағы, Қашаған Күржіманұлына арналған ескерткіш. Ұзартылған жолдан қалай шығу керек: Қарагие ойпатына түсу немесе Маңғышлақтағы Шерқала тауына тамсану.Байқоңыр - көзге көрінбейтін қала, жақын маңдағы Байқоңыр ғарыш айлағы тұтынады. , кеңестік ғарыштық бағдарламаның сайты. Бөлу үшін қанша уақыт? 1-2 күн. Негізгі көрікті жерлер: Союз зымыранының макеті, ғарыш айлағы тарихы мұражайы, Юрий Гагарин ескерткіші. Соққы жолынан қалай шығуға болады: Күнді Байқоңыр космодромында өткізіңіз (алдын-ала рұқсат қажет) немесе демалыс күндері Арал теңізіне Көкарал бөгетіне және Қаратерен ауылына барыңыз. ',		
		'c_tour5':'Сіз бұл жерлерге міндетті түрде баруыңыз керек:',
		'c_tour6':'Шарын каньоны',
		'c_tour7':'Қайыңды',
		'c_tour8':'Ақмечет-Әулие үңгірі',
		'c_tour9':'Отпан-тау',
		'c_tour10':'Арыстан-Баб',
		'f_question':'Жиі қойылатын сұрақтар (ЖҚС)',
		'f_title':'Туризм',
		'f_question2':'Шарын каньонына қашан баруға болады?',
		'f_question3':'Автобус Шарын каньонына қанша рет барады?',
		'f_question4':'Ақмечет-Әулиеге қалай жетуге болады?',
		'f_title2':'Техникалық',
		'f_question5':'Мақала қалай жариялануы мүмкін?',
		'f_question6':'Аударма сайтта жұмыс істемейді',
		'f_question7':'Түсініктемелер жұмыс істемейді',
		'f_title3':'Ынтымақтастық',
		'f_question8':'Сіз өзіңіздің сайтыңызға қалай жарнама бере аласыз?',
		'f_question9':'Сізбен қалай байланысуға болады?',
		'f_question10':'Жарнама критерийлері қандай?',
		'f_question11':'Егер сізде әлі де сұрақтар туындаса, мәселені сипаттаңыз, біз пошта арқылы жауап береміз.',
		'f_question12':'Хат жіберу',
	},
	'ru':{
		'main':'Главная',
		'help':'Помощь',
		'tour':'Туризм',
		'main2':'Сакральные места Казахстана',
		'inform':'Информация о самых широко известных мест культурного наследия',
		'more':'Подробнее',
		'Otpan':'Отпантау - историческо-культурный комплекс, мавзолей. 2007 г. Он был открыт 25 октября. Комплекс построен в 2004 году по инициативе С. Адая.',
		'Kaindy':'Каинды - озеро Алматинской области Казахстана, популярное место туризма в одном из ущелий Кунгей Алатау.',
		'Arystan':'Арыстан-Баб - мавзолей на могиле учителя и духовного наставника Ходжи Ахмеда Ясави. Мавзолей расположен в 150 километрах города Шымкента.',
		'Ak':'Акмечеть-Аулие — пещера в Туркестанской области Казахстана.',
		'A':'Акмечеть-Аулие',
		'Ch':'Чарынский каньон',
		'Charyn':'Чарынский каньон - протянувшийся на 154 км каньон вдоль реки Чарын в Казахстане.',
		'Our':'Наши соцсети:',
		'Our2':'Наша почта:',
		'c_tour':'Туризм по сакральным местам Казахстана',
		'c_text':'Путешествие в Казахстан – это настоящее приключение, полное удивительных природных пейзажей, радушия местных жителей и многообразия вкусов национальной кухни. Эта страна, расположенная на стыке Европы и Азии, впитала веяния самых разных культурных и религиозных течений. На протяжении тысячелетий на этой земле проживали кочевники, занимавшиеся выпасом скота на просторных долинах близ рек и среди живописных предгорий.В дословном переводе слово «казах» означает «свободный человек», а значит, Казахстан – страна свободолюбивого народа, который живет в мире с соседями и гордится своей историей. Как отдельное государство Республика Казахстан появилась на геополитической карте мира в 1991 году, после распада СССР. Однако в течение многих столетий казахский народ культивировал собственные, уникальные ценности, следовал принятым издревле традициям, пестовал свою кухню, музыку, народные танцы... Сегодня Казахстан – это одна из крупнейших в мире стран, которая поражает воображение гостей многообразием во всех пластах и особенностях местной жизни. Отправляйтесь в путешествие по Казахстану – и эта страна покажет вам всю яркость красок и остроту вкусов, которые стали частью ее уникального колорита.',
		'c_tour2':'Путешествие в Казахстан в разные сезоны',
		'c_text2':'Весной и осенью в Казахстане самый умеренный климат, однако благодаря огромным размерам страны наслаждаться теплой погодой можно в разных ее уголках в разное время.Зима – идеальное время для катания на лыжах, сноуборде и коньках. Сделать это можно в современных горнолыжных курортах Медеу и Шымбулак в Алматы. Также зима – отличная возможность посетить музеи, парные бани и праздничные мероприятия в крупных городах Казахстана.Осенью в Казахстане есть чем заняться, поскольку большая часть страны озаряется яркими осенними пейзажами, а погодные условия хорошо подходят для пеших прогулок и экскурсий по городам и за их пределами.Весна – это сезон походов по каньонам, изучения петроглифов, туров в Южный Туркестан и Шымкент и путешествий на поезде, где вы сможете насладиться пейзажами заснеженных гор и цветущих лугов.Лето обычно жаркое на юге и умеренное на севере страны. Летом можно как изучать столицу, так и отправиться в национальный парк Бурабай, посетить станцию Байконур или побывать на Каспийское море недалеко от Актау.Ответ на вопрос «Чем заняться в Казахстане?» может быть раскрыт сотнями вариантов ответов. В стране действительно есть всё, чтобы активно, интересно и с пользой провести бесценные дни вашего путешествия.',
		'c_tour3':'Сколько дней выделить на путешествие по Казахстану?',
		'c_text3':'Крупные города, такие как Нур-Султан и Алматы, принимают на себя большую часть туристического потока. Все они предлагают широкий выбор развлечений и вариантов досуга, помимо посещения исторических и современных достопримечательностей. Однако жаль, что большая часть природных локаций так легко игнорируется торопливыми туристами. Если вы хотите спланировать действительно увлекательное путешествие в Казахстан, изучите наше руководство и создайте собственный подробный маршрут вашего захватывающего приключения по стране.Нур-Султан (Астана) – модный и современный город Казахстана, знаменитый своей ветреной погодой и футуристической архитектурой.Как много времени выделить? 1-2 дняГлавные достопримечательности: Башня Байтерек, ТЦ «Хан-Шатыр», Дворец мира и согласия.Как сойти с проторенной дороги: совершите однодневную поездку в национальный парк Бурабай или в Коргалжынский заповедник.Алматы – бывшая столица и самый крупный город страны. В архитектурном облике Алматы впечатляюще сочетаются советский и современный стили.Как много времени выделить? 1-2 дняГлавные достопримечательности: Парк Панфилова, Зеленый базар, Алматинская канатная дорога до Кок-ТюбеКак сойти с проторенной дороги: совершите путешествие во времени, побывав в этно-деревне гуннов, которые ведут быт и хозяйство так же, как их прадеды столетия назад. Любители впечатляющих видов могут отправиться к высокогорному спортивному комплексу «Медеу», недалеко от Алматы, и обозреть пейзаж с видом на каток и окрестные горные хребты.Алматинская область – Вблизи Алматы можно найти массу локаций для однодневных поездок, которые они заслуживают особого внимания.Как много времени выделить? 2 дня (кемпинг по дороге или однодневные поездки из Алматы)Главные достопримечательности: Чарынский каньон, Большое Алматинское озеро, Тургеньское ущелье и водопад. Как сойти с проторенной дороги: полюбуйтесь петроглифами Тамгалы или разбейте лагерь в заповеднике Алтын-Эмель.',
		'c_text4':'Шымкент – большой южный город, где отлично сохранилась среднеазиатская атмосфера.Как много времени выделить? 1-2 дняГлавные достопримечательности: этнографический музей Кылует, Аллея памяти в парке Абая, улица АрбатКак сойти с проторенной дороги: осмотрите мавзолеи и продуктовый базар в селе Сайрам или покатайтесь на лошадях в заповеднике Аксу-Жабаглы.Туркестан – столица Южного Казахстана, небольшой, но древний город и святое место паломничества.Как много времени выделить? 1 деньГлавные достопримечательности: комплекс Ходжа Ахмеда Ясави с подземной мечетью, музеем, мавзолеями и городской стенойКак сойти с проторенной дороги: присоединяйтесь к религиозным паломникам в Мавзолее Арыстан Баб или побродите по руинам Отрара.Актау – город на дальнем западе, известный своей нефтью, протяженной береговой линией Каспийского моря и близостью к Кавказу.Как много времени выделить? 1 деньГлавные достопримечательности: площадь Республики, набережная и морской порт Актау, памятник Кашагану КуржиманулыКак сойти с проторенной дороги: спуститься в низину Карагие или полюбоваться горой Шеркала на Мангышлаке.Байконур – неприметный город, затмеваемый близлежащим космодромом Байконур, местом советской космической программы. Как много времени выделить? 1-2 дня. Главные достопримечательности: макет ракеты «Союз», музей истории космодрома, памятник Юрию Гагарину. Как сойти с проторенной дороги: проведите день на космодроме Байконур (требуется предварительное разрешение) или совершите поездку на выходные на Кокаральскую плотину Аральского моря и деревню Каратерен.',
		'c_tour5':'Вы обязательно должны посетить эти места:',
		'c_tour6':'Чарынский каньон',
		'c_tour7':'Каинды',
		'c_tour8':'Пещера Акмечеть-Аулие',
		'c_tour9':'Отпан-тау',
		'c_tour10':'Арыстан-Баб',
		'f_question':'Часто задаваемые вопросы (FAQ)',
		'f_title':'Туризм',
		'f_question2':'Когда доступна поездка на Чарынский каньон?',
		'f_question3':'Как часто ездеет автобус на Чарынский каньон?',
		'f_question4':'Как можно добраться до Акмечеть-Аулие?',
		'f_title2':'Технические',
		'f_question5':'Как можно опубликовать статью?',
		'f_question6':'Не работает перевод на сайте',
		'f_question7':'Не работают комментарии',
		'f_title3':'Сотрудничество',
		'f_question8':'Как можно разместить рекламу на вашем сайте?',
		'f_question9':'Как можно с вами связаться?',
		'f_question10':'Какие критерии для рекламы?',
		'f_question11':'Если у Вас остались вопросы, опишите проблему, мы ответим на почту.',
		'f_question12':'Отправить'
	},
	'en':{
		'O':'Otpantau',
		'K':'Kaindy',
		'Ar':'Arystan-Bab',
		'main':'Main',
		'help':'Support',
		'tour':'Tour',
		'main2':'Sacred places of Kazakhstan',
		'inform':'Information on the most famous cultural heritage sites',
		'more':'More',
		'Otpan':'Otpantau is a historical and cultural complex, a mausoleum. 2007 It was opened on October 25th. The complex was built in 2004 on the initiative of S. Adai.',
		'Kaindy':'Kaindy is a lake in the Almaty region of Kazakhstan, a popular tourist destination in one of the Kungei Alatau gorges.',
		'Arystan':'Arystan-Bab is a mausoleum on the grave of the teacher and spiritual mentor Khoja Ahmed Yasawi. The mausoleum is located 150 kilometers from the city of Shymkent.',
		'Ak':'Akmechet-Aulie is a cave in the Turkestan region of Kazakhstan.',
		'A':'Akmechet-Aulie',
		'Ch':'Charyn canyon',
		'Charyn':'Charyn Canyon is a 154 km long canyon along the Charyn River in Kazakhstan.',
		'Our':'Our social networks:',
		'Our2':'Our mail:',
		'c_tour':'Tourism in the sacred places of Kazakhstan',
		'c_text':'Traveling to Kazakhstan is a real adventure full of amazing natural landscapes, hospitality of local residents and a variety of tastes of national cuisine. This country, located at the junction of Europe and Asia, has absorbed the influences of a variety of cultural and religious trends. For thousands of years, nomads lived on this land, who were engaged in grazing livestock in spacious valleys near rivers and among picturesque foothills. In literal translation, the word "Kazakh" means "free man", which means that Kazakhstan is a country of freedom-loving people who live in peace with neighbors and is proud of its history. As a separate state, the Republic of Kazakhstan appeared on the geopolitical map of the world in 1991, after the collapse of the USSR. However, for many centuries, the Kazakh people cultivated their own unique values, followed ancient traditions, nurtured their cuisine, music, folk dances ... Today Kazakhstan is one of the largest countries in the world, which amazes the imagination of guests with its diversity in all layers and features. local life. Go on a trip to Kazakhstan - and this country will show you all the brightness of colors and sharpness of tastes that have become part of its unique flavor',
		'c_tour2':'Travel to Kazakhstan in different seasons',
		'c_text2':'Kazakhstan has the most temperate climate in spring and autumn, but due to the countrys sheer size, warm weather can be enjoyed in different parts of the country at different times. Winter is the perfect time for skiing, snowboarding and skating. This can be done in the modern ski resorts Medeu and Shymbulak in Almaty. Also, winter is a great opportunity to visit museums, steam baths and festive events in major cities of Kazakhstan. There is a lot to do in autumn in Kazakhstan, as most of the country is illuminated by bright autumn landscapes, and the weather conditions are good for walking and excursions in cities and beyond. Spring is the season for trekking canyons, exploring petroglyphs, tours to South Turkestan and Shymkent and traveling by train, where you can enjoy the scenery of snow-capped mountains and flowering meadows. Summers are usually hot in the south and temperate in the north of the country. In summer, you can both explore the capital and go to the Burabay National Park, visit the Baikonur station or visit the Caspian Sea near Aktau. The answer to the question "What to do in Kazakhstan?" can be revealed by hundreds of answer options. The country really has everything to actively, interestingly and usefully spend the invaluable days of your trip. ',		'c_tour3':'Сколько дней выделить на путешествие по Казахстану?',
		'c_text3': 'Large cities such as Nur-Sultan and Almaty receive most of the tourist flow. All of them offer a wide range of entertainment and leisure options in addition to historical and modern attractions. It is a shame, however, that most of the natural locations are so easily ignored by hurried tourists. If you want to plan a really fun trip to Kazakhstan, study our guide and create your own detailed itinerary for your exciting country adventure. Nur-Sultan (Astana) is a trendy and modern city in Kazakhstan, famous for its windy weather and futuristic architecture. How much time to allocate? 1-2 days Main attractions: Baiterek Tower, Khan-Shatyr shopping center, Palace of Peace and Reconciliation. How to get off the beaten track: take a day trip to Burabay National Park or Korgalzhyn Reserve. Almaty is the former capital and largest city of the country. The architectural appearance of Almaty is an impressive combination of Soviet and modern styles. How much time to allocate? 1-2 days Main attractions: Panfilov Park, Green Bazaar, Almaty cable car to Kok-Tyube How to get off the beaten track: take a trip back in time, visiting the ethno-village of the Huns, who lead their life and economy in the same way as their great-grandfathers centuries ago. Lovers of impressive views can go to the high-mountain sports complex "Medeu", near Almaty, and observe the landscape overlooking the skating rink and the surrounding mountain ranges. Almaty region - Near Almaty, you can find a lot of locations for day trips that deserve special attention. time to allocate? 2 days (camping on the way or day trips from Almaty) Main attractions: Charyn canyon, Big Almaty lake, Turgen gorge and waterfall. How to get off the beaten path: admire the petroglyphs of Tamgaly or camp at the Altyn-Emel Nature Reserve. ',	
		'c_text4': 'Shymkent is a large southern city where the Central Asian atmosphere is perfectly preserved. How much time to allocate? 1-2 days Main attractions: Ethnographic Museum Kyluet, Memory Alley in Abay Park, Arbat Street How to get off the beaten track: see the mausoleums and food market in the village of Sairam or ride horses in the Aksu-Zhabagly reserve. Turkestan is the capital of South Kazakhstan, small, but an ancient city and a holy place of pilgrimage - how much time to allocate? Day 1 Main attractions: Khoja Ahmed Yasavi complex with underground mosque, museum, mausoleums and city wall How to get off the beaten track: Join religious pilgrims at the Arystan Bab Mausoleum or wander the ruins of Otrar. Aktau is a city in the far west, famous for its oil, long coastline the line of the Caspian Sea and proximity to the Caucasus. How much time to allocate? Day 1 Main attractions: Republic Square, Aktau embankment and seaport, monument to Kashagan Kurzhimanuly How to get off the beaten track: go down to the Karagiye lowland or admire Mount Sherkala on Mangyshlak. Baikonur is an inconspicuous city, eclipsed by the nearby Baikonur cosmodrome, the site of the Soviet space program. How much time to allocate? 1-2 days. The main attractions: the model of the Soyuz rocket, the museum of the history of the cosmodrome, the monument to Yuri Gagarin. How to get off the beaten path: Spend the day at the Baikonur Cosmodrome (prior permission required) or take a weekend trip to the Aral Sea Kokaral Dam and the village of Karateren. ',		
		'c_tour5':'You should definitely visit these places:',
		'c_tour6':'Charyn canyon',
		'c_tour7':'Kaindy',
		'c_tour8':'Akmechet-Aulie cave',
		'c_tour9':'Otpan-tau',
		'c_tour10':'Arystan-Bab',
		'f_question': 'Frequently Asked Questions (FAQ)',
		'f_title': 'Tourism',
		'f_question2': 'When is a trip to the Charyn Canyon available?',
		'f_question3': 'How often does the bus go to the Charyn Canyon?',
		'f_question4': 'How can I get to Akmechet-Aulie?',
		'f_title2': 'Technical',
		'f_question5': 'How can an article be published?',
		'f_question6': 'Website translation is not working',
		'f_question7': 'Comments dont work',
		'f_title3': 'Collaboration',
		'f_question8': 'How can you advertise on your site?',
		'f_question9': 'How can I contact you?',
		'f_question10': 'What are the criteria for advertising?',
		'f_question11': 'If you have any questions, please describe the problem, we will answer your mail.',
		'f_question12': 'Submit'
	}
}

$(function(){
	$('.right_block').click(function(){
		var lang = $(this).attr('id');
		$('.lang').each(function(){
			$(this).text(arrLang[lang][$(this).attr('key')]);
		});
	});
});